"""
MPLADS Monitor — Pydantic Schemas
==================================
Request/Response schemas for API validation and serialization.
"""

from datetime import datetime, date
from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum


class RiskBand(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HouseType(str, Enum):
    LOK = "LOK"
    RAJYA = "RAJYA"


class DetectionType(str, Enum):
    RULE = "RULE"
    ML = "ML"
    SIMILARITY = "SIMILARITY"


# ─────────────────────────────────────────────────────────────────────────────
# Project Schemas
# ─────────────────────────────────────────────────────────────────────────────

class ProjectSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    project_id: int
    house_type: Optional[str] = "LOK"
    state_name: Optional[str]
    constituency_name: Optional[str]
    mp_name: Optional[str]
    city_name: Optional[str] = None
    ida_name: Optional[str] = None
    location_type: Optional[str] = "Rural"
    allocated_amount: Optional[float]
    expenditure_amt: Optional[float]
    recommended_date: Optional[date] = None
    work_status: Optional[str] = "On Going"
    dataset_source: Optional[str] = "Manual Entry / Live Submission"
    expenditure_ratio: Optional[float] = None
    project_age_days: Optional[int] = None
    is_completed: Optional[bool] = False
    is_ongoing: Optional[bool] = True
    is_overdue: Optional[bool] = False
    overall_risk_score: Optional[float] = None
    risk_band: Optional[str] = None


class NewProjectInput(BaseModel):
    state_name: str
    constituency_name: str
    mp_name: str
    allocated_amount: float = Field(..., gt=0, description="Allocated amount in INR")
    expenditure_amt: float = Field(default=0.0, ge=0, description="Expenditure amount in INR")
    work_status: str = Field(default="On Going", description="On Going | Completed | Unsanctioned")
    house_type: Optional[str] = Field(default="LOK", description="LOK | RAJYA")
    location_type: Optional[str] = Field(default="Rural", description="Rural | Urban")
    recommended_date: Optional[str] = Field(default=None, description="YYYY-MM-DD")
    letter_no: Optional[str] = Field(default=None, description="Sanction/Recommendation letter number")



class ProjectDetail(ProjectSummary):
    model_config = ConfigDict(from_attributes=True)

    tenure_name: Optional[str]
    block_name: Optional[str]
    village_name: Optional[str]
    available_limit: Optional[float]
    actual_end_date: Optional[date]
    letter_no: Optional[str]
    cost_variance_pct: Optional[float]
    days_to_complete: Optional[int]
    is_unsanctioned: Optional[bool]
    is_stalled: Optional[bool]
    district_median_amount: Optional[float]
    state_median_amount: Optional[float]
    amount_vs_district_pct: Optional[float]
    amount_vs_state_pct: Optional[float]
    mp_project_count: Optional[int]
    constituency_project_count: Optional[int]
    financial_risk_score: Optional[float]
    delay_risk_score: Optional[float]
    expenditure_risk_score: Optional[float]
    duplicate_risk_score: Optional[float]
    peer_deviation_score: Optional[float]
    ml_anomaly_score: Optional[float]
    risk_flags: Optional[Any]
    model_version: Optional[str]
    rules_version: Optional[str]
    ingested_at: Optional[datetime]


class ProjectListResponse(BaseModel):
    total: int
    page: int
    page_size: int
    projects: List[ProjectSummary]


# ─────────────────────────────────────────────────────────────────────────────
# Anomaly Schemas
# ─────────────────────────────────────────────────────────────────────────────

class AnomalyResultSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    result_id: int
    project_id: int
    detection_type: Optional[str]
    rule_name: Optional[str]
    severity: Optional[str]
    score_contribution: Optional[float]
    explanation: Optional[str]
    evidence_json: Optional[Any]
    detected_at: Optional[datetime]
    model_version: Optional[str]


class RiskExplanation(BaseModel):
    """Full explainability package for a project."""
    project_id: int
    overall_risk_score: float
    risk_band: str
    score_breakdown: Dict[str, float]  # component → score
    anomalies: List[AnomalyResultSchema]
    narrative: str  # human-readable multi-line explanation
    shap_values: Optional[Dict[str, float]] = None  # feature → SHAP contribution
    disclaimer: str = (
        "This risk score is generated by an AI-assisted system. "
        "It highlights patterns requiring attention, NOT fraud findings. "
        "Human verification is mandatory before any action."
    )


# ─────────────────────────────────────────────────────────────────────────────
# Duplicate Pair Schemas
# ─────────────────────────────────────────────────────────────────────────────

class DuplicatePairSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    pair_id: int
    project_id_a: int
    project_id_b: int
    similarity_score: float
    match_factors: Optional[Any]
    detected_at: Optional[datetime]


# ─────────────────────────────────────────────────────────────────────────────
# Audit Case Schemas
# ─────────────────────────────────────────────────────────────────────────────

class AuditCaseSchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    case_id: int
    project_id: int
    priority: str
    summary: str
    anomalies: Optional[Any]
    evidence: Optional[Any]
    recommended_action: str
    disclaimer: str
    generated_at: Optional[datetime]


# ─────────────────────────────────────────────────────────────────────────────
# Dashboard Schemas
# ─────────────────────────────────────────────────────────────────────────────

class NationalKPIs(BaseModel):
    total_allocated_crore: float
    total_recommended: int
    total_recommended_amount_crore: float
    total_sanctioned: int
    total_sanctioned_amount_crore: float
    total_completed: int
    total_completed_amount_crore: float
    total_expenditure_crore: float
    total_ongoing: int
    total_unsanctioned: int
    high_risk_projects: int
    critical_risk_projects: int
    fund_utilization_pct: float
    data_as_of: datetime


class StateRiskSummary(BaseModel):
    state_name: str
    total_projects: int
    total_allocated_crore: float
    total_expenditure_crore: float
    fund_utilization_pct: float
    high_risk_count: int
    critical_risk_count: int
    avg_risk_score: float
    delayed_projects: int


class MpRiskSummary(BaseModel):
    mp_name: str
    constituency_name: str
    state_name: str
    total_projects: int
    total_allocated_crore: float
    total_expenditure_crore: float
    fund_utilization_pct: float
    avg_risk_score: float
    high_risk_count: int


class TrendPoint(BaseModel):
    period: str        # e.g. "2023-Q2"
    projects_recommended: int
    projects_completed: int
    amount_recommended_crore: float
    amount_expended_crore: float


# ─────────────────────────────────────────────────────────────────────────────
# Search Schemas
# ─────────────────────────────────────────────────────────────────────────────

class NLSearchRequest(BaseModel):
    query: str = Field(..., min_length=3, max_length=500)


class ProjectFilter(BaseModel):
    """Safe, parameterized filter object (never raw SQL from LLM)."""
    state_name: Optional[str] = None
    constituency_name: Optional[str] = None
    mp_name: Optional[str] = None
    risk_band: Optional[List[str]] = None
    min_risk_score: Optional[float] = None
    max_risk_score: Optional[float] = None
    min_amount_lakh: Optional[float] = None
    max_amount_lakh: Optional[float] = None
    min_age_days: Optional[int] = None
    max_age_days: Optional[int] = None
    is_overdue: Optional[bool] = None
    is_completed: Optional[bool] = None
    is_ongoing: Optional[bool] = None
    has_expenditure: Optional[bool] = None
    location_type: Optional[str] = None
    sort_by: str = "overall_risk_score"
    sort_order: str = "desc"
    page: int = 1
    page_size: int = 20


class NLSearchResponse(BaseModel):
    query: str
    interpreted_as: str       # human-readable interpretation
    filter_applied: ProjectFilter
    results: ProjectListResponse
    disclaimer: str = "Results are based on pattern matching. Verify data independently."


# ─────────────────────────────────────────────────────────────────────────────
# Generic Responses
# ─────────────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    database: str
    model_version: str
    rules_version: str
    total_projects: int
    timestamp: datetime


class ErrorResponse(BaseModel):
    error: str
    detail: Optional[str] = None
