"""
MPLADS Monitor — Natural Language Explanations
================================================
Generates human-readable risk explanations for flagged projects.

Each explanation includes:
- Overall risk score and band
- Score breakdown by component
- Specific rule/ML findings with evidence
- Recommended action
- Mandatory disclaimer

Target audience: Auditors, district authorities, ministry officials
Tone: Professional, factual, non-accusatory
"""

import logging
from typing import Optional
from datetime import date

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "DISCLAIMER: This assessment is generated by an AI-assisted risk "
    "prioritization system. It identifies patterns that warrant human attention. "
    "These are RISK INDICATORS, not findings of fraud or misconduct. "
    "All flagged cases MUST be reviewed by qualified human auditors "
    "before any action is taken."
)


def format_inr(amount: float) -> str:
    """Format amount in Indian Rupees (lakhs/crores)."""
    if amount is None:
        return "N/A"
    if abs(amount) >= 1_00_00_000:
        return f"Rs {amount / 1_00_00_000:.2f} Cr"
    elif abs(amount) >= 1_00_000:
        return f"Rs {amount / 1_00_000:.2f} L"
    else:
        return f"Rs {amount:,.0f}"


def generate_risk_narrative(project: dict,
                             anomalies: list = None,
                             shap_values: dict = None) -> str:
    """
    Generate a full human-readable risk explanation for one project.
    
    Args:
        project: dict with all project fields + risk scores
        anomalies: list of anomaly result dicts for this project
        shap_values: optional dict of {feature: contribution}
    
    Returns:
        Multi-line formatted explanation string
    """
    risk_score = project.get("overall_risk_score", 0)
    risk_band = project.get("risk_band", "LOW")
    project_id = project.get("project_id", "?")

    lines = []
    lines.append(f"RISK ASSESSMENT — Project #{project_id}")
    lines.append("=" * 50)
    lines.append(f"RISK SCORE: {risk_score:.0f}/100 | {risk_band}")
    lines.append("")

    # Project summary
    lines.append("PROJECT DETAILS:")
    lines.append(f"  State: {project.get('state_name', 'N/A')}")
    lines.append(f"  Constituency: {project.get('constituency_name', 'N/A')}")
    lines.append(f"  MP: {project.get('mp_name', 'N/A')}")
    lines.append(f"  Location: {project.get('city_name') or project.get('block_name') or 'N/A'} "
                 f"({project.get('location_type', 'N/A')})")
    lines.append(f"  IDA: {project.get('ida_name', 'N/A')}")
    lines.append(f"  Allocated: {format_inr(project.get('allocated_amount'))}")
    if project.get("expenditure_amt"):
        lines.append(f"  Expenditure: {format_inr(project.get('expenditure_amt'))}")
    lines.append(f"  Recommended: {project.get('recommended_date', 'N/A')}")
    lines.append(f"  Status: {project.get('work_status', 'N/A')}")
    if project.get("project_age_days"):
        lines.append(f"  Age: {project.get('project_age_days')} days")
    lines.append("")

    # Score breakdown
    lines.append("SCORE BREAKDOWN:")
    components = [
        ("Financial", project.get("financial_risk_score", 0), 0.25),
        ("Delay", project.get("delay_risk_score", 0), 0.20),
        ("Expenditure", project.get("expenditure_risk_score", 0), 0.20),
        ("Duplicate", project.get("duplicate_risk_score", 0), 0.15),
        ("Peer Deviation", project.get("peer_deviation_score", 0), 0.10),
        ("ML Anomaly", project.get("ml_anomaly_score", 0), 0.10),
    ]
    for name, score, weight in components:
        contribution = score * weight
        bar_length = int(contribution / 2.5)
        bar = "█" * bar_length + "░" * (10 - bar_length)
        lines.append(f"  {name:18s} [{bar}] {contribution:5.1f}pts "
                     f"(score: {score:.0f} × weight: {weight})")
    lines.append("")

    # Anomaly details
    if anomalies:
        lines.append("DETECTED RISK INDICATORS:")
        for i, anom in enumerate(anomalies, 1):
            severity = anom.get("severity", "?")
            icon = "🔴" if severity == "CRITICAL" else "🟠" if severity == "HIGH" else "🟡"
            rule = anom.get("rule_name", "?")
            explanation = anom.get("explanation", "")
            lines.append(f"  {icon} [{severity}] {rule}")
            lines.append(f"     {explanation}")

            evidence = anom.get("evidence_json", {})
            if isinstance(evidence, dict):
                key_evidence = []
                for k, v in evidence.items():
                    if k not in ("disclaimer", "note", "issue") and v is not None:
                        if isinstance(v, float):
                            key_evidence.append(f"{k}: {v:.2f}")
                        elif isinstance(v, dict):
                            continue
                        else:
                            key_evidence.append(f"{k}: {v}")
                if key_evidence:
                    lines.append(f"     Evidence: {', '.join(key_evidence[:4])}")
            lines.append("")

    # SHAP explanation
    if shap_values:
        lines.append("ML MODEL FEATURE CONTRIBUTIONS (SHAP):")
        sorted_shap = sorted(shap_values.items(), key=lambda x: abs(x[1]), reverse=True)
        for fname, val in sorted_shap[:5]:
            direction = "↑ increases risk" if val > 0 else "↓ decreases risk"
            lines.append(f"  {fname}: {val:+.4f} ({direction})")
        lines.append("")

    # Recommended action
    if risk_band == "CRITICAL":
        action = ("IMMEDIATE REVIEW RECOMMENDED: Schedule physical verification, "
                  "cross-check financial records with district authority, "
                  "and verify work completion status on-ground.")
    elif risk_band == "HIGH":
        action = ("PRIORITY REVIEW: Verify financial records with implementing agency, "
                  "check work progress report, and compare with peer projects.")
    elif risk_band == "MODERATE":
        action = ("ROUTINE REVIEW: Include in next scheduled audit cycle. "
                  "Monitor progress and update status.")
    else:
        action = "No immediate action required. Standard monitoring continues."

    lines.append(f"RECOMMENDED ACTION: {action}")
    lines.append("")
    lines.append(DISCLAIMER)

    return "\n".join(lines)


def generate_audit_case(project: dict,
                         anomalies: list = None,
                         shap_values: dict = None) -> dict:
    """
    Generate a structured audit investigation case.
    
    Returns a dict suitable for the audit_cases table.
    """
    risk_score = project.get("overall_risk_score", 0)
    risk_band = project.get("risk_band", "LOW")

    # Build summary
    summary_parts = []
    summary_parts.append(
        f"Project #{project.get('project_id')} in {project.get('constituency_name', '?')}, "
        f"{project.get('state_name', '?')} scored {risk_score:.0f}/100 ({risk_band} risk)."
    )

    if anomalies:
        n_critical = sum(1 for a in anomalies if a.get("severity") == "CRITICAL")
        n_high = sum(1 for a in anomalies if a.get("severity") == "HIGH")
        if n_critical:
            summary_parts.append(f"{n_critical} CRITICAL risk indicator(s) detected.")
        if n_high:
            summary_parts.append(f"{n_high} HIGH risk indicator(s) detected.")

        rule_names = [a.get("rule_name", "?") for a in anomalies]
        summary_parts.append(f"Flagged by: {', '.join(rule_names)}")

    # Build evidence list
    evidence = {
        "project_summary": {
            "project_id": project.get("project_id"),
            "state": project.get("state_name"),
            "constituency": project.get("constituency_name"),
            "mp": project.get("mp_name"),
            "allocated_amount": project.get("allocated_amount"),
            "expenditure_amt": project.get("expenditure_amt"),
            "recommended_date": str(project.get("recommended_date", "")),
            "work_status": project.get("work_status"),
            "age_days": project.get("project_age_days"),
        },
        "risk_scores": {
            "overall": risk_score,
            "financial": project.get("financial_risk_score"),
            "delay": project.get("delay_risk_score"),
            "expenditure": project.get("expenditure_risk_score"),
            "duplicate": project.get("duplicate_risk_score"),
            "peer": project.get("peer_deviation_score"),
            "ml": project.get("ml_anomaly_score"),
        },
        "anomaly_count": len(anomalies) if anomalies else 0,
    }

    if shap_values:
        evidence["ml_feature_contributions"] = shap_values

    # Determine recommended action
    if risk_band == "CRITICAL":
        action = (
            "1. Schedule immediate physical verification of project site.\n"
            "2. Request detailed financial records from implementing agency.\n"
            "3. Cross-verify work completion claims with on-ground evidence.\n"
            "4. Compare cost estimates with similar projects in the district.\n"
            "5. Escalate to appropriate authority if discrepancies found."
        )
    elif risk_band == "HIGH":
        action = (
            "1. Include in priority audit queue for current cycle.\n"
            "2. Request progress report from implementing agency.\n"
            "3. Verify financial documentation and approval chain.\n"
            "4. Check for similar flagged projects in same constituency."
        )
    else:
        action = (
            "1. Include in routine monitoring checklist.\n"
            "2. Request status update from district authority.\n"
            "3. Flag for follow-up in next audit cycle."
        )

    return {
        "project_id": project.get("project_id"),
        "priority": risk_band,
        "summary": " ".join(summary_parts),
        "anomalies": [
            {
                "rule": a.get("rule_name"),
                "severity": a.get("severity"),
                "explanation": a.get("explanation"),
            }
            for a in (anomalies or [])
        ],
        "evidence": evidence,
        "recommended_action": action,
        "disclaimer": DISCLAIMER,
    }
