"""
Digi.MPLAD — Natural Language Explanations
==========================================
Generates clear, simple English explanations for citizens, auditors, and district authorities.

Target audience: Citizens, Community Auditors, District Collectors, and Ministry Officials.
Tone: Transparent, objective, accessible plain-English.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "CITIZEN & AUDITOR NOTICE: This assessment is generated by an automated AI-assisted audit system. "
    "It points out specific financial, timeline, or peer differences that require human verification. "
    "These indicators highlight areas for inspection and do NOT represent final legal findings of fraud. "
    "District authorities and field inspection officers must verify on-ground site conditions and measurement books."
)


def format_inr(amount: Optional[float]) -> str:
    """Format amount into easily readable Indian Rupees (Lakhs and Crores)."""
    if amount is None or amount == 0:
        return "₹0"
    if abs(amount) >= 1_00_00_000:
        return f"₹{amount / 1_00_00_000:.2f} Crore"
    elif abs(amount) >= 1_00_000:
        return f"₹{amount / 1_00_00_000 * 100:.2f} Lakhs"
    else:
        return f"₹{amount:,.0f}"


def get_plain_english_rule_explanation(rule_name: str, evidence: dict, project: dict) -> dict:
    """
    Translates technical audit rule triggers into plain English for ordinary citizens.
    """
    rule_lower = rule_name.lower()
    
    if "r001" in rule_lower or "cost overrun" in rule_lower or "expenditure > allocated" in rule_lower:
        alloc = format_inr(project.get("allocated_amount"))
        exp = format_inr(project.get("expenditure_amt"))
        diff = format_inr((project.get("expenditure_amt") or 0) - (project.get("allocated_amount") or 0))
        return {
            "title": "Extra Money Spent Beyond Approved Budget (Cost Overrun)",
            "plain_reason": f"More government money was spent on this project than what was officially approved. The sanctioned budget was {alloc}, but {exp} has been disbursed ({diff} extra).",
            "citizen_impact": "When extra money is paid without official re-approval, it risks fund leakage or billing irregularities.",
            "what_to_check": "Check the District Measurement Book (MB) and verify if a Revised Administrative Sanction was signed by the District Collector."
        }
    
    if "r002" in rule_lower or "chronic delay" in rule_lower or "age > 730" in rule_lower:
        age = project.get("project_age_days", "Over 730")
        return {
            "title": "Severe Project Delay (Ongoing for over 2 Years)",
            "plain_reason": f"This project has been active for {age} days (more than 2 full years) without being completed.",
            "citizen_impact": "MPLADS works like drinking water, roads, and community halls should finish within 1 year so local residents can benefit. Extreme delays leave citizens without essential facilities.",
            "what_to_check": "Conduct a physical site visit to inspect why construction is stalled and verify contractor milestone reports."
        }

    if "r003" in rule_lower or "age > 365" in rule_lower:
        age = project.get("project_age_days", "Over 365")
        return {
            "title": "Moderate Timeline Delay (Exceeding 1 Year)",
            "plain_reason": f"This project has been ongoing for {age} days, exceeding the standard 1-year guideline for community infrastructure.",
            "citizen_impact": "Timely completion ensures public funds are working for the community instead of dragging on.",
            "what_to_check": "Review the latest physical progress percentage with the Implementing District Authority."
        }

    if "r004" in rule_lower or "unsanctioned" in rule_lower:
        exp = format_inr(project.get("expenditure_amt"))
        return {
            "title": "Money Spent Before Official Sanction / Approval",
            "plain_reason": f"Government records show {exp} was spent on this work, but the project is still listed as 'Unsanctioned' without formal administrative approval.",
            "citizen_impact": "Under government financial rules, no contractor payments can be released before formal sanction letters are issued.",
            "what_to_check": "Verify sanction order dates in eSAKSHI and request payment vouchers from the District Treasury."
        }

    if "r005" in rule_lower or "district median" in rule_lower:
        alloc = format_inr(project.get("allocated_amount"))
        med = format_inr(project.get("district_median_amount"))
        return {
            "title": "Unusually High Cost Compared to Local Similar Projects",
            "plain_reason": f"The allocated budget of {alloc} is more than 3 times higher than typical similar projects in this constituency (average {med}).",
            "citizen_impact": "High-cost anomalies need scrutiny to verify that costs reflect real construction needs and not inflated estimates.",
            "what_to_check": "Inspect the Detailed Project Report (DPR) and schedule of rates (SoR) used by the engineering department."
        }

    if "r006" in rule_lower or "state median" in rule_lower:
        alloc = format_inr(project.get("allocated_amount"))
        med = format_inr(project.get("state_median_amount"))
        return {
            "title": "State-Level Cost Outlier",
            "plain_reason": f"The allocation of {alloc} is significantly higher than the state-wide average ({med}) for this category.",
            "citizen_impact": "Large deviations from state norms warrant a quick review of project scope and deliverables.",
            "what_to_check": "Compare bill of quantities with state public works department (PWD) benchmarks."
        }

    if "r008" in rule_lower or "stalled" in rule_lower:
        return {
            "title": "Idle / Parked Public Funds (No Progress in 1 Year)",
            "plain_reason": "Funds were allocated over a year ago, but less than 5% of the money has been spent, indicating that work has barely started.",
            "citizen_impact": "Public money is sitting locked up in government accounts instead of providing real infrastructure to the public.",
            "what_to_check": "Verify if tendering has occurred or if there are land acquisition / contractor disputes."
        }

    if "r009" in rule_lower or "duplicate" in rule_lower:
        return {
            "title": "Possible Duplicate Project",
            "plain_reason": "Another project with very similar work description, budget, and location was recommended within a short time window.",
            "citizen_impact": "Dual billing or duplicate recommendations for the same physical asset must be caught to prevent double expenditure.",
            "what_to_check": "Cross-reference GPS geo-coordinates and exact site addresses of both projects."
        }

    # Default friendly fallback
    return {
        "title": rule_name,
        "plain_reason": f"Statistical variance detected in project financial or timeline indicators.",
        "citizen_impact": "Warrants human verification to ensure full transparency and timely public service delivery.",
        "what_to_check": "Verify project documentation with the local Implementing District Authority."
    }


def generate_risk_narrative(project: dict,
                             anomalies: list = None,
                             shap_values: dict = None) -> str:
    """
    Generates a simple English explanation narrative for citizens and auditors.
    """
    risk_score = project.get("overall_risk_score", 0)
    risk_band = project.get("risk_band", "LOW")
    project_id = project.get("project_id", "?")
    mp_name = project.get("mp_name", "Hon'ble MP")
    state = project.get("state_name", "N/A")
    constituency = project.get("constituency_name", "N/A")
    allocated = format_inr(project.get("allocated_amount"))
    expended = format_inr(project.get("expenditure_amt"))
    status = project.get("work_status", "In Progress")
    age = project.get("project_age_days", 0)

    lines = []
    lines.append(f"CASE BRIEFING: Project #{project_id} ({constituency}, {state})")
    lines.append("=" * 60)
    lines.append(f"OVERALL RISK RATING: {risk_score:.0f} out of 100 ({risk_band} Priority)")
    lines.append("")
    lines.append("1. WHAT IS THIS PROJECT?")
    lines.append(f"   • Location: {constituency} Parliamentary Constituency, {state}")
    lines.append(f"   • Recommended By: {mp_name}")
    lines.append(f"   • Approved Budget: {allocated}")
    lines.append(f"   • Money Spent So Far: {expended}")
    lines.append(f"   • Current Status: {status} (Active for {age} days)")
    lines.append("")

    lines.append("2. WHY WAS THIS PROJECT FLAGGED FOR AUDIT?")
    if anomalies and len(anomalies) > 0:
        for idx, anom in enumerate(anomalies, 1):
            rule_name = anom.get("rule_name", "Risk Indicator")
            plain = get_plain_english_rule_explanation(rule_name, anom.get("evidence_json", {}), project)
            lines.append(f"   Issue #{idx}: {plain['title']}")
            lines.append(f"   • Reason: {plain['plain_reason']}")
            lines.append(f"   • Why It Matters to Citizens: {plain['citizen_impact']}")
            lines.append(f"   • Action: {plain['what_to_check']}")
            lines.append("")
    else:
        lines.append("   • No direct compliance rule violations found.")
        lines.append("   • Risk score is based on subtle differences in expenditure speed and peer comparisons.")
        lines.append("")

    lines.append("3. RECOMMENDED NEXT STEPS FOR AUDITORS & CITIZENS:")
    if risk_band == "CRITICAL":
        lines.append("   • Immediate on-site physical inspection is recommended.")
        lines.append("   • District Collectorate should cross-check measurement books and contractor bills.")
    elif risk_band == "HIGH":
        lines.append("   • Priority audit review in the current quarter.")
        lines.append("   • Request progress milestone documentation and verify completion claims.")
    elif risk_band == "MODERATE":
        lines.append("   • Routine inspection during next scheduled district review.")
    else:
        lines.append("   • Project is moving within expected timelines and normal budget parameters.")

    lines.append("")
    lines.append(f"NOTICE: {DISCLAIMER}")

    return "\n".join(lines)


def generate_audit_case(project: dict,
                         anomalies: list = None,
                         shap_values: dict = None) -> dict:
    """
    Generates a structured plain-English audit case docket for PDF export and inspection.
    """
    risk_score = project.get("overall_risk_score", 0)
    risk_band = project.get("risk_band", "LOW")
    constituency = project.get("constituency_name", "N/A")
    state = project.get("state_name", "N/A")
    allocated = format_inr(project.get("allocated_amount"))
    expended = format_inr(project.get("expenditure_amt"))

    summary = (
        f"Project #{project.get('project_id')} in {constituency} ({state}) has an approved budget of {allocated} "
        f"with {expended} spent to date. The automated audit system calculated a risk score of {risk_score:.0f}/100 ({risk_band} Priority) "
        f"based on statutory guidelines and peer project comparisons."
    )

    structured_anomalies = []
    for a in (anomalies or []):
        plain = get_plain_english_rule_explanation(a.get("rule_name", ""), a.get("evidence_json", {}), project)
        structured_anomalies.append({
            "rule": plain["title"],
            "severity": a.get("severity", "MODERATE"),
            "explanation": plain["plain_reason"],
            "action_advice": plain["what_to_check"],
        })

    if risk_band == "CRITICAL":
        action = (
            "1. Physical Site Inspection: Send an audit officer to inspect actual ground progress.\n"
            "2. Measurement Book (MB) Verification: Check contractor measurements against sanctioned DPR.\n"
            "3. Financial Cross-Check: Reconcile Treasury disbursements with District Collector approvals.\n"
            "4. Citizen Feedback: Confirm with local panchayat/ward representatives if the asset is functional."
        )
    elif risk_band == "HIGH":
        action = (
            "1. Priority Audit Review: Review work progress with the Implementing District Authority.\n"
            "2. Milestone Verification: Confirm percentage of physical work completed against money spent.\n"
            "3. Timeline Rectification: Issue directive to expedite pending construction."
        )
    else:
        action = (
            "1. Routine Monitoring: Track progress in standard monthly district reviews.\n"
            "2. Utilization Tracking: Ensure remaining balance is utilized for timely completion."
        )

    return {
        "project_id": project.get("project_id"),
        "priority": risk_band,
        "summary": summary,
        "anomalies": structured_anomalies,
        "recommended_action": action,
        "disclaimer": DISCLAIMER,
    }
