"""
MPLADS Monitor — Demo Data Generator
=====================================
Generates realistic synthetic MPLADS data for offline demo purposes.

This data is structurally identical to real MPLADS data (same columns,
realistic distributions) but is entirely synthetic. It is used for:
- Hackathon demo when portal is unreachable
- Development and testing
- Showcasing all risk categories and anomaly types

DISCLAIMER: All data generated by this script is SYNTHETIC and does NOT
represent actual MPLADS records, MPs, or projects.

Scale: ~5,000 projects across 28 states, 543 constituencies
Includes: all dataset sources, calamity data, allocation data
Contains: ~8% high/critical risk records for demo purposes
"""

import random
import json
import logging
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional
import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)

random.seed(42)
np.random.seed(42)

# ─────────────────────────────────────────────────────────────────────────────
# Reference Data (realistic but synthetic)
# ─────────────────────────────────────────────────────────────────────────────

STATES_CONSTITUENCIES = {
    "Andhra Pradesh": ["AMARAVATI", "ANAKAPALLE", "ARAKU", "BAPATLA", "CHITTOOR",
                        "ELURU", "GUNTUR", "HINDUPUR", "KAKINADA", "KURNOOL",
                        "NANDYAL", "NARASARAOPET", "NELLORE", "ONGOLE", "RAJAM",
                        "RAJAMPET", "RAJAHMUNDRY", "SRIKAKULAM", "TIRUPATI", "VISAKHAPATNAM",
                        "VIZIANAGARAM", "VIJAYAWADA"],
    "Telangana": ["ADILABAD", "BHONGIR", "CHEVELLA", "HYDERABAD", "KARIMNAGAR",
                   "KHAMMAM", "MAHABUBABAD", "MAHBUBNAGAR", "MEDAK", "MALKAJGIRI",
                   "NAGARKURNOOL", "NALGONDA", "NIZAMABAD", "PEDDAPALLI", "SECUNDERABAD",
                   "WARANGAL", "ZAHIRABAD"],
    "Maharashtra": ["AHMEDNAGAR", "AMRAVATI", "AURANGABAD", "BARAMATI", "BULDHANA",
                     "CHANDRAPUR", "DHULE", "DINDORI", "GADCHIROLI", "HINGOLI",
                     "JALGAON", "JALNA", "KOLHAPUR", "LATUR", "MAVAL",
                     "MUMBAI NORTH", "MUMBAI SOUTH", "NAGPUR", "NANDED", "NASHIK",
                     "PALGHAR", "PUNE", "RAIGARH", "RATNAGIRI", "SATARA",
                     "SHIRDI", "SHIRUR", "SOLAPUR", "THANE", "WARDHA", "YAVATMAL"],
    "Tamil Nadu": ["ARANI", "CHENNAI CENTRAL", "CHENNAI NORTH", "CHENNAI SOUTH",
                    "COIMBATORE", "CUDDALORE", "DHARMAPURI", "DINDIGUL", "ERODE",
                    "KALLAKURICHI", "KANCHEEPURAM", "KARUR", "KRISHNAGIRI",
                    "MADURAI", "MAYILADUTHURAI", "NAMAKKAL", "NILGIRIS",
                    "PERAMBALUR", "POLLACHI", "RAMANATHAPURAM", "SALEM",
                    "SIVAGANGA", "TENKASI", "THANJAVUR", "THENI", "TIRUCHIRAPPALLI",
                    "TIRUNELVELI", "TIRUPPUR", "TIRUVALLUR", "TIRUVANNAMALAI",
                    "VELLORE", "VILLUPURAM", "VIRUDHUNAGAR"],
    "Karnataka": ["BAGALKOT", "BANGALORE CENTRAL", "BANGALORE NORTH", "BANGALORE SOUTH",
                   "BELGAUM", "BELLARY", "BIDAR", "CHAMARAJANAGAR", "CHIKBALLAPUR",
                   "CHIKKODI", "CHITRADURGA", "DAVANGERE", "DHARWAD", "GULBARGA",
                   "HASSAN", "HAVERI", "KODAGU", "KOLAR", "KOPPAL",
                   "MANDYA", "MYSORE", "RAICHUR", "SHIMOGA", "TUMKUR",
                   "UDUPI-CHIKMAGALUR", "UTTARA KANNADA"],
    "Uttar Pradesh": ["AGRA", "AKBARPUR", "ALIGARH", "ALLAHABAD", "AMROHA",
                       "AZAMGARH", "BADAUN", "BAHRAICH", "BANDA", "BARABANKI",
                       "BAREILLY", "BASTI", "BHADOHI", "BIJNOR", "BUDAUN",
                       "BULANDSHAHR", "CHANDAULI", "DEORIA", "ETAH", "ETAWAH",
                       "FAIZABAD", "FARRUKHABAD", "FATEHPUR", "FIROZABAD",
                       "GAUTAM BUDDHA NAGAR", "GHAZIABAD", "GHAZIPUR", "GONDA",
                       "GORAKHPUR", "HAMIRPUR", "HARDOI", "HATHRAS", "JALAUN",
                       "JAUNPUR", "JHANSI", "KANNAUJ", "KANPUR", "KASGANJ",
                       "KAUSHAMBI", "KHERI", "KUSHINAGAR", "LAKHIMPUR", "LALITPUR",
                       "LUCKNOW", "MAHARAJGANJ", "MATHURA", "MEERUT", "MIRZAPUR",
                       "MISRIKH", "MORADABAD", "MUZAFFARNAGAR", "PHULPUR", "PILIBHIT",
                       "PRATAPGARH", "RAE BARELI", "RAMPUR", "ROBERTSGANJ",
                       "SAMBHAL", "SAHARANPUR", "SANT KABIR NAGAR", "SHAHJAHANPUR",
                       "SHRAWASTI", "SITAPUR", "SULTANPUR", "VARANASI"],
    "Bihar": ["ARARIA", "ARRAH", "AURANGABAD_BR", "BANKA", "BEGUSARAI",
               "BHAGALPUR", "BUXAR", "DARBHANGA", "GAYA", "GOPALGANJ",
               "HAJIPUR", "JAMUI", "JEHANABAD", "KATIHAR", "KHAGARIA",
               "KISHANGANJ", "MADHEPURA", "MADHUBANI", "MAHARAJGANJ",
               "MUNGER", "MUZAFFARPUR", "NALANDA", "NAWADA", "PALIGANJ",
               "PATALIPUTRA", "PATNA SAHIB", "PURNIA", "SAMASTIPUR",
               "SASARAM", "SHEOHAR", "SITAMARHI", "SIWAN", "SUPAUL",
               "UJIARPUR", "VAISHALI"],
    "Rajasthan": ["AJMER", "ALWAR", "BANSWARA", "BARMER", "BHARATPUR",
                   "BHILWARA", "BIKANER", "CHITTORGARH", "CHURU", "DAUSA",
                   "DHOLPUR", "DUNGARPUR", "GANGANAGAR", "JAIPUR", "JAIPUR RURAL",
                   "JALORE", "JHALAWAR", "JHUNJHUNU", "JODHPUR", "KARAULI",
                   "KOTA", "NAGAUR", "PALI", "RAJSAMAND", "SIKAR",
                   "SIROHI", "TONK", "UDAIPUR"],
    "Madhya Pradesh": ["BALAGHAT", "BETUL", "BHIND", "BHOPAL", "CHHINDWARA",
                        "DAMOH", "DEWAS", "DHAR", "GUNA", "GWALIOR",
                        "HOSHANGABAD", "INDORE", "JABALPUR", "JHABUA", "KHAJURAHO",
                        "KHANDWA", "KHARGONE", "MANDLA", "MANDSOUR", "MORENA",
                        "RAJGARH", "RATLAM", "REWA", "SAGAR", "SATNA",
                        "SEHORE", "SEONI", "SHAHDOL", "SIDHI", "TIKAMGARH",
                        "UJJAIN", "VIDISHA"],
    "Gujarat": ["AMRELI", "ANAND", "BANASKANTHA", "BHARUCH", "BHAVNAGAR",
                 "CHHOTA UDAIPUR", "DAHOD", "GANDHINAGAR", "GIR SOMNATH",
                 "JAMNAGAR", "JUNAGADH", "KACHCHH", "KHEDA", "MAHESANA",
                 "NAVSARI", "PANCHMAHAL", "PATAN", "PORBANDAR", "RAJKOT",
                 "SABARKANTHA", "SURAT", "SURENDRANAGAR", "VADODARA", "VALSAD"],
    "West Bengal": ["ALIPURDUAR", "ARAMBAGH", "ASANSOL", "BALURGHAT", "BANKURA",
                     "BARDHAMAN DURGAPUR", "BARDHAMAN PURBA", "BASIRHAT",
                     "BISHNUPUR", "BOLPUR", "COOCH BEHAR", "DARJEELING",
                     "DIAMOND HARBOUR", "DUM DUM", "GHATAL", "HOWRAH",
                     "JADAVPUR", "JALPAIGURI", "JANGIPUR", "JHARGRAM",
                     "JOYNAGAR", "KANTHI", "KOLKATA DAKSHIN", "KOLKATA UTTAR",
                     "KRISHNANAGAR", "MALDAHA DAKSHIN", "MALDAHA UTTAR",
                     "MATHURAPUR", "MEDINIPUR", "MURSHIDABAD", "PURULIA",
                     "RAIGANJ", "RANAGHAT", "SERAMPORE", "ULUBERIA", "VISHNUPUR"],
    "Kerala": ["ALATHUR", "ALAPPUZHA", "ATTINGAL", "CHALAKUDY", "ERNAKULAM",
                "IDUKKI", "KANNUR", "KASARAGOD", "KOLLAM", "KOTTAYAM",
                "KOZHIKODE", "MAVELIKKARA", "MUVATTUPUZHA", "PALAKKAD",
                "PATHANAMTHITTA", "PONNANI", "THRISSUR", "THIRUVANANTHAPURAM",
                "VATAKARA", "WAYANAD"],
    "Punjab": ["AMRITSAR", "ANANDPUR SAHIB", "BATHINDA", "FARIDKOT",
                "FATEHGARH SAHIB", "FEROZEPUR", "GURDASPUR", "HOSHIARPUR",
                "JALANDHAR", "KHADOOR SAHIB", "LUDHIANA", "PATHANKOT",
                "PATIALA", "RUPNAGAR", "SANGRUR"],
    "Haryana": ["AMBALA", "BHIWANI-MAHENDRAGARH", "FARIDABAD", "GURGAON",
                 "HISAR", "KARNAL", "KURUKSHETRA", "ROHTAK", "SIRSA", "SONIPAT"],
    "Odisha": ["BALASORE", "BARGARH", "BERHAMPUR", "BHUBANESWAR", "BOLANGIR",
                "CUTTACK", "DEOGARH", "DHENKANAL", "GAJAPATI", "JAGATSINGHPUR",
                "JAJPUR", "JHARSUGUDA", "KALAHANDI", "KANDHAMAL", "KENDRAPARA",
                "KEONJHAR", "KORAPUT", "MAYURBHANJ", "NABARANGPUR", "PURI",
                "RAYAGADA", "SAMBALPUR", "SUNDERGARH"],
    "Assam": ["BARPETA", "DARRANG-UDALGURI", "DHUBRI", "DIBRUGARH", "DIPHU",
               "GAUHATI", "JORHAT", "KARIMGANJ", "KOKRAJHAR", "LAKHIMPUR",
               "MANGALDOI", "NAGAON", "NOWGONG", "SILCHAR", "TEZPUR"],
}

WORK_TYPES = [
    "Construction of Road", "Repair of Road", "Construction of School Building",
    "Construction of Community Hall", "Installation of Solar Lights",
    "Construction of Drainage System", "Laying of Water Pipeline",
    "Construction of Health Sub-Centre", "Construction of Anganwadi Centre",
    "Improvement of Irrigation Canal", "Construction of Panchayat Bhawan",
    "Repair of Bridge", "Construction of Well", "Installation of Hand Pumps",
    "Construction of Sports Ground", "Construction of Library Building",
    "Laying of Concrete Path", "Construction of Boundary Wall",
    "Construction of Market Shed", "Repair of Irrigation Channel",
    "Construction of Rest House", "Installation of Water ATM",
    "Construction of Public Toilet Complex", "Development of Park",
    "Construction of Bus Shelter", "Electrification of Village",
    "Construction of Flood Protection Wall", "Construction of Check Dam",
]

MP_NAMES = [
    f"DEMO MP {i:03d}" for i in range(1, 544)
]


def random_date(start: date, end: date) -> date:
    delta = (end - start).days
    return start + timedelta(days=random.randint(0, delta))


def generate_mp_allocations(n_mps: int = 543) -> list:
    """Generate MP allocation records (Lok Sabha)."""
    records = []
    states = list(STATES_CONSTITUENCIES.keys())
    for i in range(n_mps):
        state = states[i % len(states)]
        constituencies = STATES_CONSTITUENCIES[state]
        const = constituencies[i % len(constituencies)]
        mp_name = f"MP {i+1:03d} {state[:8].upper()}"
        # Annual entitlement ~5 Cr/year, 2 years = ~10 Cr
        base_alloc = random.uniform(3_00_00_000, 15_00_00_000)
        records.append({
            "STATE_NAME": state,
            "CONSTITUENCY_NAME": const,
            "MP_NAME": mp_name,
            "ALLOCATED_AMOUNT": round(base_alloc, 2),
            "HOUSE_NAME": "LOK SABHA",
        })
    return records


def generate_projects(n_projects: int = 5000) -> list:
    """
    Generate realistic synthetic project records.
    
    Distribution:
    - 60% completed
    - 25% ongoing  
    - 10% unsanctioned
    - 5% anomalous/high-risk patterns
    """
    projects = []
    states = list(STATES_CONSTITUENCIES.keys())
    portal_launch = date(2023, 4, 1)
    today = date.today()

    anomaly_budget = int(n_projects * 0.08)  # ~8% anomalous

    for i in range(n_projects):
        state = random.choice(states)
        constituencies = STATES_CONSTITUENCIES[state]
        const = random.choice(constituencies)
        mp_name = f"HON'BLE MP {const[:8]} {random.randint(1, 3)}"

        # Recommendation date: April 2023 to 6 months ago
        rec_date = random_date(portal_launch, today - timedelta(days=30))

        # Normal amount: 1 lakh to 50 lakh (in rupees)
        base_amount = random.uniform(1_00_000, 50_00_000)

        # Inject anomaly patterns for ~8% of projects
        is_anomaly = i < anomaly_budget
        anomaly_type = None

        if is_anomaly:
            anomaly_type = random.choice([
                "cost_overrun", "extreme_amount", "very_old_ongoing",
                "expenditure_without_sanction", "stalled_funds"
            ])

            if anomaly_type == "cost_overrun":
                base_amount = random.uniform(20_00_000, 80_00_000)
            elif anomaly_type == "extreme_amount":
                # 3-10x the typical range
                base_amount = random.uniform(1_50_00_000, 5_00_00_000)
            elif anomaly_type == "very_old_ongoing":
                rec_date = random_date(portal_launch, portal_launch + timedelta(days=90))
            elif anomaly_type == "stalled_funds":
                base_amount = random.uniform(30_00_000, 1_00_00_000)

        # Determine project status
        age_days = (today - rec_date).days
        rand_val = random.random()

        if age_days < 60:
            status = "UNSANCTIONED"
            source = "Unsanctioned"
        elif rand_val < 0.55:
            status = "COMPLETED"
            source = "Completed"
        elif rand_val < 0.85:
            status = "ONGOING"
            source = "On_Going"
        else:
            status = "SANCTIONED"
            source = "On_Going"

        # Override for anomaly types
        if anomaly_type == "very_old_ongoing":
            status = "ONGOING"
            source = "On_Going"
        elif anomaly_type == "expenditure_without_sanction":
            status = "UNSANCTIONED"
            source = "Unsanctioned"

        # Expenditure
        expenditure = None
        actual_end_date = None

        if status == "COMPLETED":
            if anomaly_type == "cost_overrun":
                exp_ratio = random.uniform(1.05, 1.35)  # 5-35% overrun
            else:
                exp_ratio = random.uniform(0.85, 1.02)  # normal completion
            expenditure = round(base_amount * exp_ratio, 2)
            days_to_complete = random.randint(90, 730)
            actual_end_date = rec_date + timedelta(days=days_to_complete)
            if actual_end_date > today:
                actual_end_date = today - timedelta(days=random.randint(1, 30))

        elif status in ("ONGOING", "SANCTIONED"):
            if anomaly_type == "stalled_funds":
                exp_ratio = random.uniform(0.0, 0.03)  # barely any spend
            else:
                exp_ratio = random.uniform(0.2, 0.75)
            expenditure = round(base_amount * exp_ratio, 2)

        elif status == "UNSANCTIONED":
            if anomaly_type == "expenditure_without_sanction":
                expenditure = round(base_amount * random.uniform(0.1, 0.5), 2)
            else:
                expenditure = None

        location_type = random.choice(["Rural", "Urban", "Rural", "Rural"])  # 75% rural
        ida_name = f"{const[:6].upper()} DISTRICT AUTHORITY"

        record = {
            "HOUSE_NAME": "LOK SABHA",
            "STATE_NAME": state,
            "CONSTITUENCY_NAME": const,
            "MP_NAME": mp_name,
            "IDA_NAME": ida_name,
            "CITY_NAME": f"{const[:5]} City" if location_type == "Urban" else None,
            "BLOCK_NAME": f"{const[:5]} Block" if location_type == "Rural" else None,
            "VILLAGE_NAME": f"Village {random.randint(1, 999)}" if location_type == "Rural" else None,
            "LOCATION_TYPE": location_type,
            "WORK_STATUS": status,
            "RECOMMENDATION_DATE": rec_date.strftime("%d-%b-%Y"),
            "RECOMMENDED_AMOUNT": round(base_amount, 2),
            "FRESH_LIMIT": round(random.uniform(0, base_amount * 0.3), 2),
            "EXPENDITURE_AMT": expenditure,
            "ACTUAL_END_DATE": actual_end_date.strftime("%d-%b-%Y") if actual_end_date else None,
            "LETTER_NO": f"LTR/{state[:3].upper()}/{random.randint(10000, 99999)}/2024",
            "_dataset_source": source,
            "_is_anomaly": is_anomaly,
            "_anomaly_type": anomaly_type,
        }
        projects.append(record)

    # Shuffle so anomalies aren't all at the beginning
    random.shuffle(projects)
    return projects


def generate_calamity_consents(n: int = 50) -> list:
    """Generate calamity consent records."""
    calamities = [
        "Flood 2023 in Bihar", "Cyclone Michaung 2023", "Flood 2024 in Assam",
        "Earthquake 2023 in Uttarakhand", "Drought 2023 in Maharashtra",
        "Flood 2025 in Punjab", "Hailstorm 2024 in Rajasthan",
    ]
    states = list(STATES_CONSTITUENCIES.keys())
    records = []
    for _ in range(n):
        state = random.choice(states)
        constituencies = STATES_CONSTITUENCIES[state]
        const = random.choice(constituencies)
        mp = f"HON'BLE MP {const[:8]} {random.randint(1, 3)}"
        records.append({
            "CALAMITY_TYPE": random.choice(["National Calamity", "State Calamity"]),
            "CALAMITY_NAME": random.choice(calamities),
            "MP_NAME": mp,
            "DATE_OF_CONSENT": random_date(date(2023, 4, 1), date.today()).strftime("%d-%b-%Y"),
            "CONSENT_AMOUNT": round(random.uniform(50_00_000, 2_00_00_000), 2),
        })
    return records


def save_synthetic_data(output_dir: Path) -> dict:
    """Generate all synthetic datasets and save as JSON files."""
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Generating synthetic MPLADS demo data...")
    logger.info("NOTE: All data is SYNTHETIC for demo purposes only.")

    all_data = {}

    # Allocations
    lok_alloc = generate_mp_allocations(543)
    rajya_alloc = generate_mp_allocations(245)
    all_data["LOK_Allocated_Limit"] = lok_alloc
    all_data["RAJYA_Allocated_Limit"] = rajya_alloc[:30]  # Rajya Sabha subset

    # Projects
    projects = generate_projects(5000)

    # Split by status into separate dataset lists
    by_source = {}
    for proj in projects:
        source = proj.pop("_dataset_source", "On_Going")
        proj.pop("_is_anomaly", None)
        proj.pop("_anomaly_type", None)
        if source not in by_source:
            by_source[source] = []
        by_source[source].append(proj)

    for source, records in by_source.items():
        all_data[f"LOK_{source.replace(' ', '_')}"] = records
        logger.info(f"  {source}: {len(records)} records")

    # Calamity
    all_data["LOK_Calamity"] = generate_calamity_consents(50)
    all_data["RAJYA_Calamity"] = generate_calamity_consents(20)

    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    for key, records in all_data.items():
        filepath = output_dir / f"{key}_{timestamp}.json"
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(records, f, ensure_ascii=False, indent=2, default=str)
        logger.info(f"Saved {key}: {len(records)} records → {filepath}")

    # Manifest
    manifest = {
        "type": "SYNTHETIC_DEMO_DATA",
        "disclaimer": "All data is synthetic. Does not represent real MPLADS records.",
        "timestamp": timestamp,
        "datasets": {k: len(v) for k, v in all_data.items()},
        "total_projects": sum(len(v) for k, v in all_data.items()
                              if "Allocated_Limit" not in k and "Calamity" not in k),
    }
    with open(output_dir / f"manifest_{timestamp}.json", "w") as f:
        json.dump(manifest, f, indent=2)

    logger.info(f"Synthetic data generation complete. {sum(manifest['datasets'].values())} total records.")
    return all_data


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    out = Path(__file__).parent.parent / "data" / "raw"
    save_synthetic_data(out)
